---
title: "Predicting Ames, Iowa Housing Price"
author: "Alex Navarro"
date: "10/27/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load Packages:
library(MASS)
library(ggplot2)
library(markdown)
library(knitr)
library(RColorBrewer)
library(Sleuth2)
# Read data into system:
data <- read.csv("AmesHousing.csv")
```
# Exploratory Data Analysis
```{r, echo=TRUE}
# Set Seed to Save Models:
set.seed(1)

# check head of dataframe:
head(data, n = 10)

# Look at structure of dataframe:
str(data)

# Look at missing values in dataframe:
summary(data)
```

```{r, echo=TRUE}
# Remove Missing Values from Data:
data2= na.omit(data)
# check structure of dataframe:
str(data2)

# Split Training Set 70/30
train <- sample(2258,1800)
test <- (c(1:2258)[-train])

# Create a data frame with continuous variables only:
num.ames =data.frame(data2[,c(2,3,14:17,23,31,33:35,40:49,51,53,56,58,59,63:68,70,71,74)])

# Checking Data Correlation and Distribution:
plot(SalePrice ~., data = num.ames, subset = train)
```
# Modeling:
```{r, echo=TRUE}
# Create First Model:
fit <- lm(SalePrice ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + TotRms.AbvGrd +
            Garage.Yr.Blt + Wood.Deck.SF +  Open.Porch.SF, data = num.ames, subset = train)

# Return model summary of first model:
summary(fit)

# Create Second Model:
fit2 <- lm(SalePrice ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + TotRms.AbvGrd +
            Garage.Yr.Blt + Wood.Deck.SF, data = num.ames, subset = train)
# Return model summary of second model:
summary(fit2)

# Create Third Model:
fit3 <- lm(SalePrice ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Garage.Yr.Blt + Wood.Deck.SF, data = num.ames, subset = train)
# Return model summary of third model:
summary(fit3)
```
# Check Model Diagnostics:
```{r, cache=TRUE}
# Plot Fitted vs Residuals:
plot(fit3$res~fit3$fitted, main = "Fitted vs Residuals")
# Check normality of model:
hist(fit3$res, main = "Normality Test",
     col = c("blue", "red", "green"))
# Plot qq-plot:
qqnorm((fit3$res))
# add reference line:
qqline(fit3$res)
# Compute Shapiro-Wilk Test for Normality Check:
shapiro.test(fit3$res)
```
# Boxcox Transformation:
```{r, cache=TRUE}
# Run boxcox transformation to help normalize data:
boxcox(SalePrice~Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + TotRms.AbvGrd +
         Garage.Yr.Blt + Wood.Deck.SF, data = num.ames)
# Create new variable that is the log of SalesPrice:
num.ames$SalePriceLog <- log(num.ames$SalePrice)

# Create new model using SalesPriceLog for the dependent variable:
fit4 <- lm(SalePriceLog~Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + TotRms.AbvGrd +
         Garage.Yr.Blt + Wood.Deck.SF, data = num.ames)

# Plot Fitted vs Residual Values:
plot(fit4$res~fit4$fitted, main = "Diagnostic Check Model 4")
```
# Determine Categorical Variables For Model:
```{r,cache=TRUE}
# Which Categorical Variables Should be Included:
# Create Model One:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Model Two:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street, data = data2, subset = train)
# Run Anova:
anova(model1,model2)
# Create Model One:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Model Two:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config, data = data2, subset = train)
# Execute Anova:
anova(model1,model2)
# Create Model One:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Model Two:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation, data = data2, subset = train)
# Execute Anova:
anova(model1,model2)
# Create Model 1:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation + Bsmt.Exposure, data = data2, subset = train)
anova(model1,model2)
# Create Model 1:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Model 2:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation + Bsmt.Exposure + Heating.QC, data = data2, subset = train)
# Execute Anova:
anova(model1,model2)
# Create Model 1:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Model 2:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation + Bsmt.Exposure + Heating.QC + Central.Air, data = data2, subset = train)
# Execute Anova:
anova(model1,model2)
# Create Final Model:
model1 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF, data = data2, subset = train)
# Create Final Second Model:
model2 = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation + Bsmt.Exposure + Heating.QC + Central.Air + Functional, data = data2, subset = train)
# Execute Anova:
anova(model1,model2)

# New Model: Both Numeric and Non-Numeric:
fitnew = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + Open.Porch.SF + Street + Lot.Config + Foundation + 
    Bsmt.Exposure + Heating.QC, data = data2, subset = train)
# Run Summary of Model:
summary(fitnew)

# Remove Final Variables and Rerun Model:
fitnew = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + Open.Porch.SF+ Foundation + 
    Bsmt.Exposure + Heating.QC, data = data2, subset = train)
# Run Summary of Model:
summary(fitnew)
```
# Check Diagnostics:
```{r, echo = TRUE}
plot(fitnew$res~fitnew$fitted, main = "Residuals vs Fitted")
# Check Skewedness of Model:
hist(fitnew$res, main = "Diagnostic Check Model Histogram",
     col = c("blue", "red", "green"))
# Normality Test:
qqnorm((fitnew$res))
# Reference Line:
qqline(fitnew$res)
# Shapiro-Wilkins Test:
shapiro.test(fitnew$res)
```
# Run Test Data:
```{r, echo = TRUE}
#Final Model:
final_final = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + Open.Porch.SF+ Foundation + 
    Bsmt.Exposure + Heating.QC, data = data2, subset = test)
# Summary Final Model:
summary(final_final)

# Remove Foundation:
#Final Model:
final_final = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + Open.Porch.SF+ 
    Bsmt.Exposure + Heating.QC, data = data2, subset = test)
# Summary Final Model:
summary(final_final)

# Remove Open.Porch:
#Final Model:
final_final = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + Foundation + 
    Bsmt.Exposure + Heating.QC, data = data2, subset = test)
# Summary Final Model:
summary(final_final)

# Remove Foundation:
#Final Model:
final_final = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + Total.Bsmt.SF + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF + 
    Bsmt.Exposure + Heating.QC, data = data2, subset = test)
# Summary Final Model:
summary(final_final)

# Remove Total.Bsmt.SF:
#Final Model:
final_final = lm(num.ames$SalePriceLog ~ Overall.Qual + Year.Built + Year.Remod.Add + 
    BsmtFin.SF.1 + X1st.Flr.SF + Gr.Liv.Area + 
    Wood.Deck.SF +
    Bsmt.Exposure + Heating.QC, data = data2, subset = test)
# Summary Final Model:
summary(final_final)
```
# Final Check Diagnostics:
```{r, echo = TRUE}
plot(final_final$res~final_final$fitted, main = "Residuals vs Fitted")
# Check Skewedness of Model:
hist(final_final$res, main = "Diagnostic Check Model Histogram",
     col = c("blue", "red", "green"))
# Normality Test:
qqnorm((final_final$res))
# Reference Line:
qqline(final_final$res)
# Shapiro-Wilkins Test:
shapiro.test(final_final$res)
```